#!/usr/bin/env bash
# Sets up nginx

sudo apt-get update
sudo apt-get -y install nginx

sudo sh -c 'echo "
server {
    listen 80;

    location / {
        return 200 \"Hello World!\n\";
    }
}" > /etc/nginx/sites-available/default'

sudo systemctl restart nginx
