#!/usr/bin/env bash
# Installs and configures Nginx in web server Nginx

sudo apt update

sudo apt install -y nginx

echo 'server {
    listen 80;
    server_name _;

    location / {
        default_type text/html;
        return 200 "Hello World!";
    }
}' | sudo tee /etc/nginx/sites-available/hello-world > /dev/null

sudo ln -s /etc/nginx/sites-available/hello-world /etc/nginx/sites-enabled/

sudo rm /etc/nginx/sites-enabled/default

sudo nginx -t

sudo systemctl restart nginx
