#!/usr/bin/env bash
# Redirects

sudo apt-get update
sudo apt-get -y install nginx

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

sudo sed -i '/location \/ {/a \
\
    location /redirect_me {\
        return 301 http://www.youtube.com/watch?v=QH2-TGUlwu4;
    }' /etc/nginx/sites-available/default

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

sudo service nginx restart
