#!/usr/bin/env bash
# Redirects


sudo apt update
sudo apt install -y nginx

redirect_url="https://www.youtube.com/watch?v=QH2-TGUlwu4"

sudo sed -i.bak '/location \/redirect_me {/!b;n;c\        return 301 '"$redirect_url"';' /etc/nginx/sites-available/default

sudo service nginx restart
